require 'time'

task :hello do
  puts "hello Rake"
end

task :hello_name, [:name] do |task, args|
  puts "Hello " + args[:name]
end 

task :specs, [:tags] do |task, args|
  time = Time.now.localtime.iso8601.tr(":", "")
  report = "--format html --out=log/report_#{time}.html"
  sh "cucumber #{args[:tags]} #{report}"
end

#sh = shell